version: '3.8'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./allure-results:/app/allure-results
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app
    command: ["bash", "-c", "pytest -s --alluredir=allure-results && allure serve allure-results"]
